image:
  file: .gitpod.Dockerfile

ports:
  - name: Zot registry
    description: Test OCI registry
    port: 5000
    visibility: public

tasks:
  - name: Install Tools
    command: |
      brew install trivy
      brew tap interlynk-io/interlynk
      brew install sbomasm sbomqs
      brew install parlay
      brew tap bomctl/bomctl
      brew install bomctl
      brew install oras
  - name: Launch Zot
    command: |
      docker run -d -p 5000:5000 --name oras-quickstart ghcr.io/project-zot/zot-linux-amd64:latest

  - name: Display Help
    command: |
      gp open README.md
