image:
  file: .gitpod.Dockerfile

tasks:
  - name: Install Tools
    command: |
      brew install trivy
      brew tap interlynk-io/interlynk
      brew install sbomasm sbomqs
      brew install parlay
  - name: Display Help
    command: |
      gp open README.md
